name: df_async_loader
description: "A new Flutter project."

version: 1.0.0+1

homepage: https://dartforce.dev/
repository: https://github.com/DartForce22/df_async_loader
license: MIT

platforms:
  android:
  ios:

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
